# Generated by Django 4.2.4 on 2024-01-11 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_team_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='plan',
        ),
    ]
