apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: curl-pod
  name: curl-pod
spec:
  serviceAccountName: curl
  containers:
  - command:
    - sleep
    - "99999"
    image: curlimages/curl
    name: curl-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
