apiVersion: v1
kind: Pod
metadata:
  name: test-zimbra-pod
spec:
  hostname: mail
  subdomain: baotrung
  containers:
  - name: zimbra-container
    image: jorgedlcruz/zimbra:latest
    ports:
        - containerPort: 25
        - containerPort: 80
        - containerPort: 110
        - containerPort: 143
        - containerPort: 443
        - containerPort: 465
        - containerPort: 587
        - containerPort: 993
        - containerPort: 995
        - containerPort: 7071
        - containerPort: 8080
        - containerPort: 8443
        - containerPort: 9071
    env:
      - name: PASSWORD
        value: 0435626533a@
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
    - 127.0.0.1
    - 8.8.8.8
