# Generated by Django 4.2.4 on 2024-01-18 07:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_team_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0005_leadfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeadFile',
            new_name='ClientFile',
        ),
    ]
